name: Deploy para EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Copiar arquivos via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 15.228.249.205
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/scb-api"

    - name: Executar deploy remoto
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 15.228.249.205
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/scb-api
          git pull
          source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
          pip install -r requirements.txt
          fuser -k 8000/tcp || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > log.txt 2>&1 &
